#!/bin/bash
# This script is the entry point for the SageMaker container.

# Start the Nginx server in the background
nginx -c /opt/program/nginx.conf

# Start the Gunicorn server to run the Flask application
# It listens on a Unix socket, which Nginx is configured to use.
gunicorn --workers 1 --bind unix:/tmp/gunicorn.sock -k gevent wsgi:app